from contracts.application import Application, ApplicationPreset


def presets() -> list[ApplicationPreset]:
    return [
        ApplicationPreset(
            id="alpha-low",
            title="ООО «Альфа»",
            subtitle="Низкий риск",
            scenario="low_risk",
            application=Application(
                application_id="A142",
                company_name="ООО «Альфа»",
                segment="sme",
                industry="wholesale",
                region="moscow",
                company_age_months=74,
                annual_revenue=84_000_000,
                revenue_growth=0.11,
                ebitda_margin=0.18,
                debt_to_revenue=0.43,
                requested_amount=12_000_000,
                requested_term=24,
                credit_history_months=68,
                overdue_30d_count=0,
                overdue_90d_count=0,
                bureau_score=812,
                existing_loans_count=1,
                industry_risk=0.22,
                region_risk=0.18,
            ),
        ),
        ApplicationPreset(
            id="beta-border",
            title="ООО «Бета Трейд»",
            subtitle="Пограничная заявка",
            scenario="borderline",
            application=Application(
                application_id="B208",
                company_name="ООО «Бета Трейд»",
                segment="sme",
                industry="construction",
                region="novosibirsk",
                company_age_months=28,
                annual_revenue=36_000_000,
                revenue_growth=0.02,
                ebitda_margin=0.08,
                debt_to_revenue=0.67,
                requested_amount=18_000_000,
                requested_term=36,
                credit_history_months=22,
                overdue_30d_count=1,
                overdue_90d_count=0,
                bureau_score=690,
                existing_loans_count=3,
                industry_risk=0.48,
                region_risk=0.36,
            ),
        ),
        ApplicationPreset(
            id="gamma-high",
            title="ИП Сергеев",
            subtitle="Высокий риск",
            scenario="high_risk",
            application=Application(
                application_id="C331",
                company_name="ИП Сергеев",
                segment="sme",
                industry="retail",
                region="saratov",
                company_age_months=11,
                annual_revenue=9_400_000,
                revenue_growth=-0.18,
                ebitda_margin=0.02,
                debt_to_revenue=1.12,
                requested_amount=7_500_000,
                requested_term=18,
                credit_history_months=8,
                overdue_30d_count=4,
                overdue_90d_count=2,
                bureau_score=512,
                existing_loans_count=5,
                industry_risk=0.71,
                region_risk=0.55,
            ),
        ),
        ApplicationPreset(
            id="delta-one-minus",
            title="АО «Дельта Логистик»",
            subtitle="Сильный клиент с одним минусом",
            scenario="single_negative",
            application=Application(
                application_id="D414",
                company_name="АО «Дельта Логистик»",
                segment="sme",
                industry="logistics",
                region="spb",
                company_age_months=96,
                annual_revenue=210_000_000,
                revenue_growth=0.14,
                ebitda_margin=0.16,
                debt_to_revenue=0.81,
                requested_amount=28_000_000,
                requested_term=24,
                credit_history_months=90,
                overdue_30d_count=0,
                overdue_90d_count=0,
                bureau_score=834,
                existing_loans_count=2,
                industry_risk=0.25,
                region_risk=0.16,
            ),
        ),
        ApplicationPreset(
            id="epsilon-conflict",
            title="ООО «Эпсилон Фуд»",
            subtitle="Противоречивые данные",
            scenario="conflicting",
            application=Application(
                application_id="E505",
                company_name="ООО «Эпсилон Фуд»",
                segment="sme",
                industry="food",
                region="kazan",
                company_age_months=40,
                annual_revenue=58_000_000,
                revenue_growth=0.31,
                ebitda_margin=0.21,
                debt_to_revenue=0.38,
                requested_amount=22_000_000,
                requested_term=48,
                credit_history_months=14,
                overdue_30d_count=2,
                overdue_90d_count=0,
                bureau_score=640,
                existing_loans_count=1,
                industry_risk=0.33,
                region_risk=0.62,
            ),
        ),
        ApplicationPreset(
            id="zeta-manual",
            title="ООО «Зета Капитал»",
            subtitle="Ручное рассмотрение",
            scenario="manual_review",
            application=Application(
                application_id="F620",
                company_name="ООО «Зета Капитал»",
                segment="sme",
                industry="it",
                region="moscow",
                company_age_months=19,
                annual_revenue=140_000_000,
                revenue_growth=0.42,
                ebitda_margin=0.09,
                debt_to_revenue=0.58,
                requested_amount=55_000_000,
                requested_term=36,
                credit_history_months=16,
                overdue_30d_count=0,
                overdue_90d_count=0,
                bureau_score=748,
                existing_loans_count=4,
                industry_risk=0.29,
                region_risk=0.14,
            ),
        ),
    ]


def preset_by_id(preset_id: str) -> ApplicationPreset | None:
    return next((item for item in presets() if item.id == preset_id), None)
